### ISSUE TITLE
Path mirroring 

### ISSUE THREAD

**Issue by lidor51** [mjansen4857/pathplanner#140]
Old versions of Path Planner had both horizontal and vertical mirroring, could help adding it back.

**Comment by mjansen4857** [comment]
This was excluded because I want to avoid adding things that increase complexity and make the code messy if they aren't going to really be used. 

Flipping the path horizontally isn't really useful, as 0,0 should be on your side of the field so the fact that 0,0 in pathplanner is the blue alliance doesn't really matter as it can be considered any alliance. 

Flipping the path vertically isn't really that useful either. In 2018/2019, sure, but not really since then. If this year's game could make use of it I'll add it, but I don't want to bother with it now just for it to go unused. I'd want to do it in a way that is "visible" and not just some hidden keyboard shortcut only a handful of people will know about.
