### ISSUE TITLE
At Stop Point Allow For Un-smooth Curvature 

### ISSUE THREAD

**Issue by ohowe1** [mjansen4857/pathplanner#163]
<img width="170" alt="The straight curvature line from the PathPlanner UI" src="https://user-images.githubusercontent.com/42757516/203699657-0550e105-4e99-4ac2-a86b-4afb1341a70b.png">

Would it make sense for at a stop point to allow for the curvature lines to not be one and to allow for it to be separate on each side of it?

**Comment by WarrenReynolds** [comment]
It makes sense for swerve drive, but what about regular tank drive.  You would with have a violent turn on the stop at the start of the 2nd segment because the robot is trying to accelerate the centre point of the robot while at the same time trying to correct the heading.  For tank drive I'm thinking this might cause errors in path following.  Even for swerve drie robots all of your modules are going to be facing the wrong way as the 2nd segment is starting. I know the delay in getting them to face the correct would be very small but again it does introduce inconsistency's

A work around would be to shorten the tangent handle on the 2nd leg and then add another waypoint that is in the direction you want to head in but very close to the stop point.  This pretty much does what you want and also give a tank drive robot a short distance to perform its turn.

**Comment by ohowe1** [comment]
> It makes sense for swerve drive, but what about regular tank drive.

When I was thinking about this it was in regard to swerve, so probably would be a holonomic exclusive feature considering your point.

> A work around would be to shorten the tangent handle on the 2nd leg and then add another waypoint that is in the direction you want to head in but very close to the stop point. This pretty much does what you want and also give a tank drive robot a short distance to perform its turn.

Yeah, I'm aware of the workaround, just thought it would be better to not have to work around it.

**Comment by mjansen4857** [comment]
The biggest issue I have with this is that paths can be loaded as a single path, ignoring stop points. If someone were to try to do this with a break in the path at the stop point it would generally break the path following. I'm not sure if this is exactly what happens, but I believe in a case like this the generation would enter an infinite loop. It would see the break as a curve with 0 radius, and slow down to 0 to not go into that curve too fast. Once its at 0, it can't make forward progress so it can't speed up and just sort of gets stuck there.

So the options for dealing with this are:
1. Throw an exception if you try to load a path with uncoupled headings at a stop point. This is pretty annoying because if you want to test a path without stopping at stop points you would have to make sure you remove all of these breaks, changing the path you want to test.
2. Make a change that would stop the infinite loop. Doesn't really help much as the robot would either still need to slow down significantly, defeating the purpose of ignoring stop points, or go straight through it and cause a bunch of wheel slip and ruin your accuracy.
3. Make a smooth path out of 1 of the 2 decoupled control points. Then which one do you choose? They could result in wildly different paths depending on their placement, and either way will not be the path that you made.
4. Just let it happen. Then people are going to run into this and not understand what's happening.

I just don't think there's that much of a benefit to decoupled headings to justify any of these drawbacks. You can usually get a smooth path that is pretty close to what heading breaks would do by adjusting your point placements.

Obviously there is a benefit, but I don't think its that significant. I will do some playing around with it to see if I can find an implementation for it that I'm happy with.
