### ISSUE TITLE
CommandGroupBase class appears to be on the way out.

### ISSUE THREAD

**Issue by WarrenReynolds** [mjansen4857/pathplanner#176]
I was just looking at WPILib and noticed that a recent PR modified a bunch of command group stuff.  
[WPILib Pull Request 4728](https://github.com/wpilibsuite/allwpilib/pull/4728)

I don't think the changes will break PathPlanner in 2023, but I think the line below might need to be updated before CommandGroupBase disappears all together.  As far as I can tell it appears to be depreciated. I only found this line from CTRL+F "CommandGroupBase"

https://github.com/mjansen4857/pathplanner/blob/b57e0083ba9e31baee8a3aa814809177df995c6d/pathplannerlib/src/main/java/com/pathplanner/lib/auto/BaseAutoBuilder.java#L151

**Comment by mjansen4857** [comment]
Not going to make a change for this yet. 2024 will also have a change to merge the Command and CommandBase classes so that will need more changes. Removing use of CommandGroupBase would also need a bit of a rework of some auto builder stuff since I would lose the ability to use the addCommands method. Since there's no real benefit to switching now, I will just wait and do all of these changes at the same time for 2024.

Maybe I end up doing it anyways before the season, but there's no rush.
