### ISSUE TITLE
List of markers

### ISSUE THREAD

**Issue by Nyxiad** [mjansen4857/pathplanner#177]
Not a duplicate of issue #138. That issue is talking about an events list
When markers are close enough to each other to overlap, you can't click on markers below another. I suggest making a list of markers to select from.

**Comment by mjansen4857** [comment]
So I don't want to make really significant changes to the UI at this point since I do plan to redo a bunch of marker-related things next year, as I talked about in #138. But, I think a simple way of taking care of this for now would be to add "next marker" and "previous marker" buttons to the edit marker card.

I would also recommend avoiding markers that close together anyways if you can avoid it. But there are situations where you can't so I will work on that.
