### ISSUE TITLE
Implementations should be replaced with interfaces in parameter types.

### ISSUE THREAD

**Issue by JCodeShelver** [mjansen4857/pathplanner#179]
It is generally not recommended to structure code to take in or return objects of an implementation type, rather the interface type. This lets users of the given api use whatever implementation they want. In SwerveAutoBuilder.java (and there may be more examples), the constructor takes in a HashMap<String, Command>, but Java convention is to take in Map<String, Command>.

**Comment by mjansen4857** [comment]
I used HashMap because I wanted to force the O(1) access time, but I suppose it can be left open to use whatever you want. I think there may be uses of ArrayList instead of List in some places too, but I think I remember doing that specifically because I needed ArrayList methods not present in the List interface. I can take a look at those cases later to see if that's still true.
