### ISSUE TITLE
Path overshoots endpoint in Preview and IRL, but not in Graph

### ISSUE THREAD

**Issue by randomstring** [mjansen4857/pathplanner#195]
I made a simple path that drives forward 2 meters and stops. When I run preview in the GUI the robot clearly overshoots the endpoint and has to backtrack to hit the target endpoint. The robot also does this in real life. Looking at the velocity graph, there is no overshoot.

![pathplanner_bounce](https://user-images.githubusercontent.com/1033976/210155337-37e84e18-b2f7-4081-9c31-d95a893b0bb7.gif)

<img width="1266" alt="Screenshot 2022-12-31 at 12 40 38 PM" src="https://user-images.githubusercontent.com/1033976/210155343-6808c627-af69-4a2b-b37e-1c8bb9331c09.png">

This is using holonomic mode. I can include the path details, but it is just driving straight forward for 2 meters without any rotation, max velocity 2m/s, max acceleration 2m/s^2.

Is this a bug? Why is the back tracking not included in the graph?

**Comment by mjansen4857** [comment]
It is in the graph, you just don't notice it because the back tracking you are seeing is still decelerating at -2mps^2.

The backtracking itself is happening because of you control point placement. It should look like this:
![image](https://user-images.githubusercontent.com/9343077/210155527-6efc6836-edf6-4e71-8c50-c3ebf960c527.png)

not like this:
![image](https://user-images.githubusercontent.com/9343077/210155528-a99ee3ba-da6f-4c28-8dc8-f03009bf51f5.png)


You have the heading of your endpoint set to 180 which is why the robot travels in the 180 direction at the end of the path.

**Comment by randomstring** [comment]
Yes. That's exactly what the problem was. I had the final heading set to 180 instead of the desired 0 degrees.

I'm impressed that PathPlanner succeeds at making my impossible request of driving straight to a point from the left, but also arrive from the right come true.
