### ISSUE TITLE
useAllianceColor in any BaseAutoBuilder is mirroring the red alliance robot over the x axis instead of the y.

### ISSUE THREAD

**Issue by 1266devilduckies** [mjansen4857/pathplanner#222]
When using RamseteAutoBuilder and setting useAllianceColor to true, the red alliance paths are being mirrored over the x axis of the field instead of the y. We first thought this was a problem with our odometry but looking at the PathPlannerTrajectory class it seems that the field width and height are flipped.

Here's a chiefdelphi post with more info: https://www.chiefdelphi.com/t/pathplanner-trajectory-mirrors-on-x-instead-of-y/423757

**Comment by mjansen4857** [comment]
This is working as expected. Mirroring over Y would not transform the path for the red alliance. Due to the non-standard field mirroring, it needs to be mirrored over the X axis. Also, since (0, 0) should always be on your side of the field regardless of alliance color, it should not be mirrored over Y to preserve the correct X coordinates.
