### ISSUE TITLE
Add option to run events and path in parallel

### ISSUE THREAD

**Issue by JulianOrteil** [mjansen4857/pathplanner#285]
An option should be added to allow events and the path to run in parallel.

Consider the following case, assuming a robot with a long boom-like arm:

- A mid-path stop point with "closeGripper" and "pivotHome" events is created
- When the robot arrives at this stop point, it has its arm in a ground pickup position
- Due to mechanical specifics, attempting to pivot the arm without retracting the boom may cause damage from this position
- "pivotHome" is a sequential command group where the boom is retracted a certain amount before the arm pivots

As it currently stands, the robot waits for the "pivotHome" event to finish before continuing with the path. This takes many seconds. Having the option (a checkbox under "Execution Behavior"?) to tell PathPlanner to run the events and the path in parallel would be great.

For a specific implementation that might be ideal:
- wrapper ParallelCommandGroup
  - PathPlanner followTrajectory
  - User event commands

**Comment by WarrenReynolds** [comment]
A couple of options here without changing anything.

Use a marker event at position x.01 instead of a stop point event. where x in the point number on the path.
or
Create a dummy command that lasts only for 0.1 of a second and then use a parallel deadline at the stop point with this event as the first event in the parallel group.  Then it will move off as soon as the deadline event is finished.
