### ISSUE TITLE
Map arrow keys to move path point

### ISSUE THREAD

**Issue by Chris2fourlaw** [mjansen4857/pathplanner#303]
Feature request: For a selected path point, allow the arrow keys to translate the point up-down-left-right

**Comment by mjansen4857** [comment]
I'd like to keep keyboard traversal enabled. So, instead of using the arrow keys to translate a selected waypoint, this will be implemented as using the arrow keys to increment the value in a text field. This also has the benefit of working for things besides position. Such as heading, rotations, etc.
