### ISSUE TITLE
Allow selection of multiple points

### ISSUE THREAD

**Issue by Chris2fourlaw** [mjansen4857/pathplanner#305]
Feature request:
Allow the user to select multiple points for editing

Scenarios:
- Selecting points to delete
- Translating all points using #303

**Comment by mjansen4857** [comment]
With the new reworks I don't believe this is necessary. The path tree shows you a list of all waypoints so deleting them is pretty quick. And selecting multiple points to move them around would probably take longer than just applying the same edit to a handful of points in the tree. Especially since text fields support arithmetic, just type "+0.1" in to each waypoint's X position field if you wanted to move them all 0.1m in the x direction, for example.
