### ISSUE TITLE
Ability to add jerk and heading in radians as an option for csv export

### ISSUE THREAD

**Issue by minglethepringle** [mjansen4857/PathPlanner#33]
Fantastic path planner by the way. Thank you!

I'm looking to export it and then simply plop it into Pathfinder (V1), but it doesn't allow anything except a "perfect" CSV, which includes jerk and heading (in radians, not degrees) as headers. If jerk could be calculated and heading have a configuration for radians or degrees, that would be awesome!

**Comment by mjansen4857** [comment]
Added this in 678192b. Since there isn't much space in the settings window for a setting that most people probably won't use I added the option to output in radians as a hidden setting. You will need to manually edit the settings file located at `{USER HOME}/.PathPlanner/settings.json` and add this entry: `"outputRadians": true` to enable the setting.
