### ISSUE TITLE
No deceleration when approaching stop point with velocity override

### ISSUE THREAD

**Issue by shueja-personal** [mjansen4857/pathplanner#351]
[New Path.path.txt](https://github.com/mjansen4857/pathplanner/files/12644629/New.Path.path.txt)

Replication path above. 
Steps to reproduce:
1. Have a path with 3+ waypoints. 
2. Add a velocity override to the middle one (I used 1 m/s) above
3. Mark the middle point as a stop point.
4. Watch the robot fail to decelerate before stopping at the middle waypoint. The velocity graph backs this up.
![image](https://github.com/mjansen4857/pathplanner/assets/32416547/f5212412-5cc2-4b63-a93f-b252cf5fc38f)
5. Set the middle point as a reversal (and not a stop), see a similar graph. Set it to reversal and stop, and the graph is the same as reversal. 

All three cases exhibit some sort of conflict between the velocity override and the reversal/stop making velocity be 0.

Expected Behavior:
Reversal and stop points should completely ignore any provided velocity override, and the trajectory should decelerate to 0 ahead of the point.

**Comment by mjansen4857** [comment]
Its a weird edge case caused by how stop points used to work internally, the override velocity is only being applied to the start point of the second path. All of this is changed in the 2024 version as the concepts of velocity override, stop points, and reversal points have all been replaced by a zoned constraints system and modular paths, so this bug isn't present anymore.
