### ISSUE TITLE
Java Error on Run

### ISSUE THREAD

**Issue by jasondaming** [mjansen4857/PathPlanner#4]
After installing I get this error:
![image](https://user-images.githubusercontent.com/15695521/51536599-c337c480-1e11-11e9-9088-6e3b694d4fb6.png)

This is on a surface pro Windows 10 installed through both windows store and .exe

**Comment by mjansen4857** [comment]
I've had this error a few times myself on different machines. It's caused by the nodejs local storage module and there doesn't seem to be anything consistent about when it happens so I made a commit recently to move away from that module. The error is fixed but not released yet. You can try building from source or I will probably release an update today.
