### ISSUE TITLE
Issues with following a holonomic path

### ISSUE THREAD

**Issue by SecretGenius22** [mjansen4857/pathplanner#449]
I have been working on our swerve drive robot for a while now and I have finally gotten to auto. I used pathplanner last year with our differential drivetrain and got it working very well, but now I am having issues with the holonomic mode. The robot does not rotate at all in auto to try and follow paths I've created, even though the editor is in holonomic mode and in telemetry it shows the ideal path rotating while the robot does not. I tried pathing through autos, paths, and creating a manual path with bezier points, but none of it worked. Any help is appreciated, thanks. 
Code here: https://github.com/team223/223-Robot-Project-Pre-Season-2024

**Comment by mjansen4857** [comment]
This is more of a general swerve drive support thing, so I'd recommend making a post about it over on Chief Delphi or something like that if you have a preferred place. There will be more people there able to help out for stuff like this.

Anyways, it looks like the issue is that you're using your swerve module motor PID values for the PID values given to the auto builder. Because of this, the values are so small that they will essentially do nothing, which is why it won't rotate. You will want a separate set of values for the ones given to auto builder.
