### ISSUE TITLE
PathPlanner sometimes after deploy has paths that do not follow the written path at all.

### ISSUE THREAD

**Issue by PGtheVRguy** [mjansen4857/pathplanner#459]
**Describe the bug**
When deploying paths via the Windows PathPlanner on Windows 10 over ethernet on a swerve based robot, the deploy will be successful, but has strange effects where the robot will move in strange ways, and it is entirely unpredictable when the deploy will do this.

**To Reproduce**
Hit deploy via pathplanner 2023 over Ethernet.

**Expected behavior**
The path will be deployed and run successfully, but what happens is the path moves in a unpredictable way.

![image](https://github.com/mjansen4857/pathplanner/assets/46075828/b6d99415-0a89-446d-9cf7-313899dcfcac)
This is the path that we run, however our drive coach and I believe that this could be the path not flipping towards the red alliance side. In the video you can see the fault where it runs through the path of 2H, but the bot itself moves into the wrong direction. We also saw this problem before a few comps ago. If needed, I can try and find those videos. 
https://www.youtube.com/watch?v=SRZZrRkCh_s
(Watch 7211 on Red Alliance, that is our bot!)

**Versions: (please complete the following information):**
 - OS: [Windows 10]
 - GUI Version: [2023.4.2]
 - PPLib Version: [2023.4.2] (I think)
 - PPLib Language: [Java]

**Comment by mjansen4857** [comment]
Based on the video you linked, this looks like a gyro failure. Notice how it continues to drive backwards robot-relative as it rotates when leaving the community. This indicates that the gyro is probably not working here since the path following commands attempt to drive field relative. Driving field relative without a working gyro essentially just ends up being robot relative.

**Comment by mjansen4857** [comment]
Closing since its probably a gyro issue
