### ISSUE TITLE
Pathplanner applies last chassis speeds when interrupting a path with a race group.

### ISSUE THREAD

**Issue by domilx** [mjansen4857/pathplanner#620]
**Describe the bug**
When I put a path in a race group with intake for example, if the command finishes earlier than the path, the robot just stalls in the last direction it was pointed in. 

**Expected behavior**
It should just cut the robot's ChassisSpeeds to 0

**Versions:**
 - OS: Windows 11
 - GUI Version: 2024.1.4
 - PPLib Language: Java

**Comment by mjansen4857** [comment]
This is intended. If a path following command is interrupted, it is up to the user to make sure new speeds are applied to the drive train depending on their use case. This could either be coming to a stop, or continuing to move towards something else without stopping. So, the path following command will not output 0 speeds so that it does not interfere with trying to maintain speed into another command.
