### ISSUE TITLE
Export a shareable representation of auto

### ISSUE THREAD

**Issue by rjbell4** [mjansen4857/pathplanner#642]
**Is your feature request related to a problem? Please describe.**
It's difficult to efficiently communicate multiple Auto options with other teams.

**Describe the solution you'd like**
Some way to visually export a path -- print it, export as a GIF/PNG, etc.  Open to better suggestions, but it would be great to "flip through" Autos with an alliance partner and find out what's compatible.

**Comment by WarrenReynolds** [comment]
To add to this it would be great to be able to preview the paths as they would run if you are on the Red alliance.  We just did a regional and found it hard to demonstrate to other teams where we start and go if we were Red. While we had gotten used to the flipping in our heads it was difficult for teams that weren't using path planner to work it out when we showed them our auto from the blue side when were red. It could be as simple as while CTRL + ALT are held the paths and animation are drawn on the opposite side of the field.  (Or any other key combination)

An even better option would be the ability to have a switchable mode so that if you wanted to build an auto based on Red references you could.  I still believe that it should be stored as a "blue auto" in the json with all references to the 0,0 being in the blue corner, but if it could be drawn on the Red end it would be a nice feature.   This feature would have helped us greatly as our less than a 1/3 size practice field was build from the Red side.

**Comment by ModBoyex** [comment]
I could see a GIF export being very helpful. Our team often carry a clipboard around to show other teams what Autos we have, but I could very well see using GIFs as a great way to demonstrate what we can do in auto, and for putting into tech documents and stuff.
