### ISSUE TITLE
Make the Optimize Path option not go outside the field perimeter.

### ISSUE THREAD

**Issue by AydenLo17** [mjansen4857/pathplanner#768]
When you click optimize path for a straight path next to the field barriers, it tries to swoop out through the field perimeter. May be beneficial to make it not be possible to go outside of the field perimeter to ensure no wall collisions.

<img width="960" alt="image" src="https://github.com/user-attachments/assets/fb8e9b4c-7bd0-4edb-ac5e-15a654a9190d">
<img width="960" alt="image" src="https://github.com/user-attachments/assets/8a2f9114-c4a9-41f9-ab1e-4df14b85d929">

**Comment by mjansen4857** [comment]
Fixing by preventing the optimization results from exiting the field as long as the waypoints of the original path have no possibility of exiting the field.

It uses the radius of the robot to determine this, since it doesn't know the rotation of the robot until after generation, and it is a pretty large optimization to determine an optimization result is invalid before generation. So as a result, the path you used as an example will probably still do this, but if you move the start point to prevent the robot from being outside of the wall at any rotation(it will show the radius when you select the waypoint), it will avoid the field wall.
